version: '3.9'

services:
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment: # Corregido (enviroment -> environment)
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db # Corregido (monogo_data -> mongo_data)

